"""Subclass of LabelDlg, which is generated by wxFormBuilder."""

import wx

import CL
import UCommon

# Implementing LabelDlg
class ULabelDlg( CL.LabelDlg ):
	def __init__( self, parent ):
		CL.LabelDlg.__init__( self, parent )
		self.parent = parent

	# Handlers for LabelDlg events.
	def OnCancel( self, event ):
		# TODO: Implement OnCancel
		self.EndModal(0)

	def OnPreView( self, event ):
		# TODO: Implement OnPreView
		self.Execute(False)

	def OnExec( self, event ):
		# TODO: Implement OnExec
		self.Execute(True)
		self.EndModal(1)

	def Execute(self, Flag):
		"""処理実行
		"""
		msize = self.m_spinCtrl47.GetValue()
		if Flag:
			self.cv_image = self.cv_image.labeling_paint(msize)
			self.bitmap.SetBitmap(UCommon.uopencv2wxbitmap(self.cv_image, self.magnification))
			self.parent.RetDlg.LabelingResult(self.cv_image)
		else:
			ret_img = self.cv_image.labeling_paint(msize)
			self.bitmap.SetBitmap(UCommon.uopencv2wxbitmap(ret_img, self.magnification))
			self.parent.RetDlg.LabelingResult(ret_img)
