"""Subclass of LogDlg, which is generated by wxFormBuilder."""

import wx

import CL

# Implementing LogDlg
class ULogDlg( CL.LogDlg ):
	def __init__( self, parent ):
		CL.LogDlg.__init__( self, parent )

	# Handlers for LogDlg events.
	def OnSaveLog( self, event ):
		# TODO: Implement OnSaveLog
		dialog = wx.FileDialog(None, "ファイルを選択", wildcard="テキストファイル(UTF-8)(txt)|*.txt", style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT)
		if dialog.ShowModal() == wx.ID_OK:
			path = dialog.GetPath()
			self.m_textCtrl1.SaveFile(path)
		dialog.Destroy()

	def DispLog(self, cv_image):
		"""画像処理履歴を表示する
		"""
		self.Show(True)
		self.m_textCtrl1.Clear()
		for log in cv_image.log:
			self.m_textCtrl1.AppendText(log + '\n')
