"""Subclass of LWin, which is generated by wxFormBuilder."""

import copy

import wx

import CL
import UCommon

# Implementing LWin
class ULWin( CL.LWin ):
	def __init__( self, parent ):
		CL.LWin.__init__( self, parent )
		self.parent = parent  # 親ウインドウの関数を使うため

	# Handlers for LWin events.
	def OnMvEnd( self, event ):
		# TODO: Implement OnMvEnd
		pos = self.GetPosition()
		self.parent.ChildWinPoint = pos + wx.Point(20,20)

	def OnOpen( self, event ):
		# TODO: Implement OnOpen
		self.parent.OpenImgFile()

	def OnSaveAs( self, event ):
		# TODO: Implement OnSaveAs
		UCommon.SaveAs(self)

	def OnWClose( self, event ):
		# TODO: Implement OnWClose
		self.Close()

	def OnExit( self, event ):
		# TODO: Implement OnExit
		self.parent.OnExit(event)

	def OnCopy( self, event ):
		# TODO: Implement OnCopy
		UCommon.CopyToClipboard(self.cv_image)

	def OnPaste( self, event ):
		# TODO: Implement OnPaste
		self.parent.CopyFromClipboard()

	def OnZoomIn( self, event ):
		# TODO: Implement OnZoomIn
		UCommon.ZoomIn(self)

	def OnZoomOut( self, event ):
		# TODO: Implement OnZoomOut
		UCommon.ZoomOut(self)

	def OnZoomRst( self, event ):
		# TODO: Implement OnZoomRst
		UCommon.ZoomRst(self)

	def OnViewLog( self, event ):
		# TODO: Implement OnViewLog
		self.parent.LogDlg.DispLog(self.cv_image)

	def OnAbout( self, event ):
		# TODO: Implement OnAbout
		UCommon.About()

	def OnLDwn( self, event ):
		# TODO: Implement OnLDwn
		pos = event.GetPosition()
		x = int(pos.x / self.magnification)
		y = int(pos.y / self.magnification)
		self.parent.RetDlg.ViewItem(self.cv_image, x, y)


