"""Subclass of MonoDlg, which is generated by wxFormBuilder."""

import wx

import CL
import UCommon

# Implementing MonoDlg
class UMonoDlg( CL.MonoDlg ):
	def __init__( self, parent ):
		CL.MonoDlg.__init__( self, parent )

	# Handlers for MonoDlg events.
	def OnCancel( self, event ):
		# TODO: Implement OnCancel
		self.EndModal(0)

	def OnPreView( self, event ):
		# TODO: Implement OnPreView
		self.Execute(False)

	def OnExec( self, event ):
		# TODO: Implement OnExec
		self.Execute(True)
		self.EndModal(1)

	def Execute(self, Flag):
		"""処理実行
		"""
		color = self.m_colourPicker1.GetColour()  # カラーは color(米国英語) ではなく colour(英国英語) であることに注意
		b = color.Blue()
		g = color.Green()
		r = color.Red()
		if Flag:
			self.cv_image = self.cv_image.monotone(b, g, r)  # 変更してしまう
			self.bitmap.SetBitmap(UCommon.uopencv2wxbitmap(self.cv_image, self.magnification))
		else:
			ret_img = self.cv_image.monotone(b, g, r)        # 仮に変更する
			self.bitmap.SetBitmap(UCommon.uopencv2wxbitmap(ret_img, self.magnification))
