"""Subclass of PseudDlg, which is generated by wxFormBuilder."""

import cv2
import wx

import CL
import UCommon

# Implementing PseudDlg
class UPseudDlg( CL.PseudDlg ):
	def __init__( self, parent ):
		CL.PseudDlg.__init__( self, parent )

	# Handlers for PseudDlg events.
	def OnCancel( self, event ):
		# TODO: Implement OnCancel
		self.EndModal(0)

	def OnPreView( self, event ):
		# TODO: Implement OnPreView
		self.Execute(False)

	def OnExec( self, event ):
		# TODO: Implement OnExec
		self.Execute(True)
		self.EndModal(1)

	def Execute(self, Flag):
		"""処理実行
		"""
		if self.m_radioBtn12.GetValue():  # switch文がないので、みっともない気がする
			colormap = cv2.COLORMAP_JET
		elif self.m_radioBtn14.GetValue():
			colormap = cv2.COLORMAP_RAINBOW
		elif self.m_radioBtn11.GetValue():
			colormap = cv2.COLORMAP_BONE
		elif self.m_radioBtn15.GetValue():
			colormap = cv2.COLORMAP_PLASMA
		elif self.m_radioBtn17.GetValue():
			colormap = cv2.COLORMAP_SPRING
		elif self.m_radioBtn16.GetValue():
			colormap = cv2.COLORMAP_SUMMER
		elif self.m_radioBtn1.GetValue():
			colormap = cv2.COLORMAP_AUTUMN
		elif self.m_radioBtn13.GetValue():
			colormap = cv2.COLORMAP_WINTER

		if Flag:
			self.cv_image = self.cv_image.applyColorMap(colormap)
			self.bitmap.SetBitmap(UCommon.uopencv2wxbitmap(self.cv_image, self.magnification))
		else:
			ret_img = self.cv_image.applyColorMap(colormap)
			self.bitmap.SetBitmap(UCommon.uopencv2wxbitmap(ret_img, self.magnification))
